'use client';
import {useState} from 'react';
import {supabase} from '@/lib/supabase';
const labels={TARGET_CID_INVALID:'เลขบัตรแถวหลักไม่ถูกต้อง',CID_CONFLICT:'ทั้งสองแถวมีเลขบัตรต่างกัน',BIRTH_DATE_CONFLICT:'วันเกิดต่างกัน',ALREADY_LINKED:'มีการเชื่อมรหัสอยู่แล้ว ต้องตรวจโดยผู้ดูแล',SOURCE_ALREADY_IMPORTED:'แถวซ้ำเคยนำเข้า HOSxP แล้ว',DEMOGRAPHIC_QUEUE_PENDING:'มีคิวส่งข้อมูลบุคคลค้างอยู่',AUTHEN_APPROVAL_EXISTS:'มีการอนุมัติ Authen ของแถวซ้ำแล้ว',HISTORY_DATE_CONFLICT:'มีประวัติคัดกรองประเภทเดียวกันในวันเดียวกัน',OTHER_DUPLICATE_CID:'ยังมีแถวอื่นใช้เลขบัตรเดียวกัน',IDENTITY_NOT_UNIQUE:'ไม่พบหรือพบข้อมูล HOSxP ซ้ำ',IDENTITY_HN_CONFLICT:'HN ใน HOSxP ขัดแย้ง',IDENTITY_BIRTH_DATE_CONFLICT:'วันเกิดไม่ตรงกับ HOSxP',IDENTITY_SOURCE_ALREADY_IMPORTED:'แถวซ้ำมี VN ใน HOSxP แล้ว',IDENTITY_CHANGED_OR_CONFLICT:'ข้อมูลเปลี่ยนหรือขัดแย้ง กรุณาตรวจใหม่',IDENTITY_REQUEST_EXPIRED:'คำขอเกิน 24 ชั่วโมง กรุณาตรวจใหม่'};
const label=k=>labels[k]||(k.endsWith('_LATEST_CONFLICT')?'ผลคัดกรองล่าสุดขัดกัน ('+k.split('_')[0]+')':k);
async function rpc(name,args={}){const {data,error}=await supabase.rpc(name,args);if(error)throw Error(error.message);return data;}
export default function PersonIdentity(){
 const [query,setQuery]=useState(''),[rows,setRows]=useState([]),[source,setSource]=useState(''),[target,setTarget]=useState(''),[plan,setPlan]=useState(null),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[jobs,setJobs]=useState([]);
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError('ดำเนินการไม่สำเร็จ: '+e.message);}finally{setBusy(false);}}
 function choose(which,id){which==='source'?setSource(id):setTarget(id);setPlan(null);setConfirm(false);setNotice('');}
 return <details className="card mb-4"><summary className="card-header">เชื่อมรหัสบุคคล / จัดการแถวซ้ำ (เจ้าหน้าที่)</summary><div className="card-body">
  <p>เลือกแถวซ้ำและแถวหลักที่มีเลขบัตรถูกต้อง ตรวจผลทั้งสองแถวก่อนยืนยัน ตัวเชื่อม LAN จะตรวจรหัส HOSxP และประวัตินำเข้าซ้ำ แถวเดิมจะเก็บเป็นประวัติและหยุดรับการบันทึกใหม่</p>
  <p className="small text-muted">ย้ายเฉพาะประวัติคัดกรองและรายการเตรียม FIT ที่ยังไม่เคยนำเข้า ข้อมูลบ้าน อสม. และข้อมูลสำรวจอื่นใช้ของแถวหลัก ไม่รวมบุคคลจากชื่อโดยอัตโนมัติ</p>
  <form className="d-flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();run(async()=>setRows(await rpc('person_identity_search',{p_query:query})));}}><input className="form-control" aria-label="ค้นหาบุคคลเพื่อเชื่อมรหัส" placeholder="ชื่อ เลขบัตรครบ 13 หลัก หรือรหัสบุคคล" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><button className="btn btn-outline-primary" disabled={busy||query.trim().length<2}>ค้นหา</button></form>
  {rows.map(r=><div key={r.person_id} className="border rounded p-2 my-2"><strong>{r.fname} {r.lname}</strong> — บ้าน {r.house} หมู่ {r.moo}<div>รหัส {r.person_id} • เลขบัตรท้าย {r.cid_tail||'ไม่มี'} • วันเกิด {r.birth_date||'ไม่ระบุ'}</div>{r.canonical_id?<div>รวมแล้ว → {r.canonical_id}</div>:<div className="d-flex gap-2 mt-2"><button disabled={busy} className="btn btn-outline-warning" onClick={()=>choose('source',r.person_id)}>เลือกเป็นแถวซ้ำ</button><button disabled={busy} className="btn btn-outline-success" onClick={()=>choose('target',r.person_id)}>เลือกเป็นแถวหลัก</button></div>}{r.hn&&<small>เชื่อม HOSxP แล้ว: HN {r.hn}</small>}</div>)}
  <p className="mt-3">แถวซ้ำ: {source||'-'} → แถวหลัก: {target||'-'}</p>
  <button className="btn btn-primary" disabled={busy||!source||!target||source===target} onClick={()=>run(async()=>{setPlan(await rpc('person_identity_preview',{p_source:source,p_target:target}));setConfirm(false);})}>ตรวจข้อมูลก่อนรวม</button>
  {plan&&<div className="mt-3"><div className="table-responsive"><table className="table"><thead><tr><th>ข้อมูล</th><th>แถวซ้ำ</th><th>แถวหลัก</th></tr></thead><tbody>{[['ชื่อ',p=>p.fname+' '+p.lname],['วันเกิด',p=>p.birth_date],['เลขบัตรท้าย 4',p=>p.cid?.slice(-4)],['HBV/HCV',p=>[p.hep_screen,p.hep_date].join(' / ')],['FIT',p=>[p.fobt_screen,p.fobt_date].join(' / ')],['HPV',p=>[p.hpv_screen,p.hpv_date].join(' / ')],['พัฒนาการเด็ก',p=>[p.child_dev,p.child_date].join(' / ')]].map(([name,get])=><tr key={name}><th>{name}</th><td>{get(plan.source)||'-'}</td><td>{get(plan.target)||'-'}</td></tr>)}</tbody></table></div>
   <p>ประวัติคัดกรองรวม {plan.histories.length} รายการ • รายการเตรียม FIT {plan.preparations.length} รายการ</p>
   {plan.histories.map(h=><div key={h.id} className="small">{h.person_id===source?'แถวซ้ำ':'แถวหลัก'}: {h.kpi} • {h.result||'-'} • {h.screen_date||'-'}</div>)}
   {plan.reasons.length>0?<div className="alert alert-warning">ต้องแก้ข้อขัดแย้งก่อน: {plan.reasons.map(label).join(' / ')}</div>:<><label className="form-label d-block mt-2">เหตุผลและหลักฐานที่ตรวจแล้ว<textarea className="form-control" value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} disabled={busy}/></label><label className="d-flex gap-2 my-3"><input type="checkbox" checked={confirm} disabled={busy} onChange={e=>setConfirm(e.target.checked)}/>ยืนยันว่าเป็นบุคคลเดียวกัน และเลือกแถวหลักถูกต้อง ตรวจผลและวันที่แล้ว</label><button className="btn btn-warning" disabled={busy||!confirm||reason.trim().length<10} onClick={()=>run(async()=>{await rpc('person_identity_request',{p_source:source,p_target:target,p_fingerprint:plan.fingerprint,p_reason:reason,p_confirm:confirm});setPlan(null);setConfirm(false);setNotice('ส่งคำขอแล้ว รอ LAN ตรวจและรวมข้อมูล กรุณาตรวจสถานะด้านล่าง');setJobs(await rpc('person_identity_status'));})}>ยืนยันส่งให้ LAN ตรวจและรวมแถว</button></>}
  </div>}
  {error&&<div role="alert" className="alert alert-danger mt-2">{error}</div>}{notice&&<div role="status" className="alert alert-info mt-2">{notice}</div>}
  <button className="btn btn-outline-secondary mt-3" disabled={busy} onClick={()=>run(async()=>setJobs(await rpc('person_identity_status')))}>ตรวจสถานะคำขอ</button>
  {jobs.map(j=><div className="border-bottom py-2" key={j.id}>{j.source_id} → {j.target_id}: {{pending:'รอ LAN ตรวจ',applying:'กำลังรวม',completed:'รวมสำเร็จ',blocked:'ระงับ ต้องตรวจใหม่'}[j.state]}{j.error_code&&<div>{label(j.error_code)}</div>}</div>)}
 </div></details>;
}
