'use client';
import {useState} from 'react';
import {supabase} from '@/lib/supabase';
const labels={pending_registry_check:'รอตัวเชื่อมตรวจทะเบียน',requires_hosxp_registration:'รอลงทะเบียนใน HOSxP',linked:'เชื่อมทะเบียนแล้ว',blocked:'ต้องตรวจสอบข้อมูล'};
const reasons={HOSXP_REGISTRATION_REQUIRED:'เพิ่มทะเบียนผ่าน HOSxP แล้วรอซิงก์',PERSON_REGISTRATION_REQUIRED:'มีผู้ป่วยแล้ว ให้เพิ่ม/เชื่อมทะเบียนบัญชี 1 ใน HOSxP',PATIENT_REGISTRATION_REQUIRED:'มีบัญชี 1 แล้ว ให้ตรวจทะเบียนผู้ป่วยและ HN',IDENTITY_NOT_UNIQUE:'พบทะเบียนซ้ำ ต้องตรวจสอบก่อนเชื่อม',IDENTITY_HN_CONFLICT:'HN ในทะเบียนบุคคลและผู้ป่วยไม่ตรงกัน',IDENTITY_BIRTH_DATE_CONFLICT:'วันเกิดไม่ตรงกัน',IDENTITY_LINK_CONFLICT:'รหัสเชื่อมขัดแย้งหรือมีทะเบียนเว็บซ้ำ'};
export default function RegistrationStatus(){
 const [rows,setRows]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');try{const r=await supabase.rpc('screening_registration_status');if(r.error)throw Error();setRows(r.data||[]);}catch{setError('โหลดสถานะไม่สำเร็จ กรุณาตรวจว่าติดตั้งส่วนทะเบียนแล้วและลองใหม่');}finally{setBusy(false);}}
 return <section className="container py-2"><details onToggle={e=>{if(e.currentTarget.open&&rows===null&&!busy)load();}}><summary>ทะเบียนบุคคลใหม่และสถานะเชื่อม HOSxP</summary><p className="small mt-2">100 รายการล่าสุด • หากยังไม่มีทะเบียน ให้ลงทะเบียนผ่าน HOSxP ก่อน ตัวเชื่อมจะตรวจ CID, วันเกิด และ HN อีกครั้ง</p><button className="btn btn-sm btn-outline-primary mb-2" disabled={busy} onClick={load}>{busy?'กำลังโหลด…':'รีเฟรชสถานะ'}</button><p role="status">{error}</p><div className="table-responsive"><table className="table table-sm"><thead><tr><th>ชื่อ–นามสกุล</th><th>สถานะ</th><th>ขั้นตอนต่อไป</th><th>ตรวจล่าสุด</th></tr></thead><tbody>{rows?.map(r=><tr key={r.person_id}><td>{r.fname} {r.lname}</td><td>{labels[r.state]||'รอตรวจสอบ'}</td><td>{reasons[r.error_code]|| (r.state==='linked'?'พร้อมใช้ทะเบียนที่เชื่อมแล้ว':'รอตรวจในรอบซิงก์')}</td><td>{r.checked_at?new Date(r.checked_at).toLocaleString('th-TH'):'ยังไม่ได้ตรวจ'}</td></tr>)}</tbody></table>{rows?.length===0&&<p>ยังไม่มีคำขอเพิ่มบุคคล</p>}</div></details></section>;
}
